branches:
  only:
    - debug-travis
    - master

dist: trusty

osx_image: xcode8.3

language: cpp

os:
  - osx
  - linux

compiler: clang

addons:
  apt:
    packages:
      - gfortran
      - liblzma-dev
      - libsqlite3-dev
      - libc++-dev
      - libomp5
      - libomp-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . tools/ci/before_install-osx.sh; fi

script:
  - tools/ci/build.sh
cache:
  - ccache
