branches:
  only:
    - debug-travis
    - master

language: cpp

os:
  - osx
  - linux

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8.3

compiler: clang

addons:
  apt:
    packages:
      - gfortran
      - liblzma-dev
      - libsqlite3-dev
      - libc++-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . tools/ci/before_install-osx.sh; fi

script:
  - tools/ci/build.sh
cache:
  - ccache
