branches:
  only:
    - master

dist: trusty

language: cpp

os:
  - osx
  - linux

compiler: clang

addons:
  apt:
    packages:
      - gfortran
      - liblzma-dev
      - libsqlite3-dev
      - libc++-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then . ./tools/ci/before_install-osx.sh; fi

script:
  - export CCACHE_CPP2=yes
  - export CC="ccache clang"
  - export CXX="ccache clang++ -std=c++14 -stdlib=libc++"
  - sh configure --with-blas --with-lapack --without-ICU --without-x --without-tcltk --without-aqua --without-recommended-packages --without-internal-tzcode --with-included-gettext --enable-rdt
  - make -j5

cache:
  - ccache
