dist: trusty

language: cpp

os: linux

compiler: clang

addons:
  apt:
    packages:
      - gfortran
      - liblzma-dev
      - libsqlite3-dev

script:
  - CC="clang" CXX="clang++" ./configure --with-blas --with-lapack --without-ICU --without-x --without-tcltk --without-aqua --without-recommended-packages --without-internal-tzcode --with-included-gettext --enable-rdt
  - make -j5

