title: R-dyntrace
#logo: /assets/img/logo.png
description: A Dynamic Tracing framework for R
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  owner_name: Aviral Goel
  owner_url: https://github.com/aviralg
