#!/bin/bash

export CPPFLAGS="-g3 -O2 -ggdb3"
export CFLAGS="-g3 -O2 -ggdb3"
export R_KEEP_PKG_SOURCE=yes
export CXX="g++"

./configure --with-blas --with-lapack --without-ICU --with-x        \
            --with-tcltk --without-aqua --with-recommended-packages \
            --without-internal-tzcode --with-included-gettext       \
            --disable-byte-compiled-packages --enable-dyntrace &&
make clean &&
make -j

