#!/bin/bash

export CPPFLAGS="-g3 -O0 -ggdb"
export CFLAGS="-g3 -O0 -ggdb"
export R_KEEP_PKG_SOURCE=yes
export CXX="g++"

./configure --with-blas --with-lapack --without-ICU --without-x \
            --without-tcltk --without-aqua --without-recommended-packages \
            --without-internal-tzcode --with-included-gettext \
            --disable-byte-compiled-packages --enable-dyntrace &&
make clean &&
make -j

