---
params: 
    title: "?"
    dbpath: "?"
title: "`r params$title`"
date: "`r Sys.Date()`"
output: 
    html_document:
        theme: flatly
        highlight: pygments
---

---
<style>
    body .main-container {
        max-width: 2000px;
    }
</style>

```{r libraries, echo = FALSE, include=FALSE}
library(tidyr)
library(dplyr)
library(dbplyr)
library(ggplot2)
library(ggthemes)
library(knitr)
library(DT)
```

```{r utilities, echo = FALSE, include=FALSE}
typename <- function(type) {
    switch(toString(type),
           "0" = "NIL",
           "1" = "SYM",
           "2" = "LIST",
           "3" = "CLO",
           "4" = "ENV",
           "5" = "PROM",
           "6" = "LANG",
           "7" = "SPECIAL",
           "8" = "BUILTIN",
           "9" = "CHAR",
           "10" = "LGL",
           "13" = "INT",
           "14" = "REAL",
           "15" = "CPLX",
           "16" = "STR",
           "17" = "DOT",
           "18" = "ANY",
           "19" = "VEC",
           "20" = "EXPR",
           "21" = "BCODE",
           "22" = "EXTPTR",
           "23" = "WEAKREF",
           "24" = "RAW",
           "25" = "S4",
           "30" = "NEW",
           "31" = "FREE",
           "99" = "FUN",
           "?")
}

eventname <- function(event) {
    switch(toString(event),
           "0" = "CREATED",
           "1" = "LOOKED UP",
           "2" = "GARBAGE COLLECTED",
           "?")
}
```

```{r render_settings, echo = FALSE, include = FALSE}
opts_chunk$set(comment=NA, fig.width=22, fig.height=12)
```


```{r ggplot_theme, include = FALSE, echo = FALSE}
promise_theme <- 
    theme_minimal() +
    theme(plot.title =element_text(size = 30, face="bold", hjust = 0.5, lineheight = 4, margin = margin(t = 0, r = 0, b = 20, l = 0)),
          axis.text = element_text(size=15),
          axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5), 
          axis.title = element_text(size=20, face="bold", hjust = 0.5),
          axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)),
          axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)))

# Set promise_theme as the default theme. Store previous theme.
previous_theme <- theme_set(promise_theme)
```

```{r tables, include = FALSE, echo = FALSE}
db <- src_sqlite(params$dbpath)
functions <- db %>% tbl("functions")
arguments <- db %>% tbl("arguments")
calls <- db %>% tbl("calls")
promises <- db %>% tbl("promises")
associations <- db %>% tbl("promise_associations")
evaluations <- db %>% tbl("promise_evaluations")
lifecycle <-
    db %>%
    tbl("promise_lifecycle") %>%
    group_by(promise_id, event_type) %>%
    summarize(gc_trigger_counter = max(gc_trigger_counter))

trigger <- db %>% tbl("gc_trigger")
type_distribution <- db %>% tbl("type_distribution")
```

```{r gc_data, echo = FALSE}
gc_data <-
    lifecycle %>%
    group_by(gc_trigger_counter, event_type) %>%
    summarize(`PROMISES` = count(promise_id)) %>%
    collect() %>%
    rowwise() %>%
    mutate(gc_trigger_counter = gc_trigger_counter + (event_type < 2)) %>%
    mutate(event_type = eventname(event_type)) %>%
    rename(`PROMISE TYPE` = event_type, `GC TRIGGER` = gc_trigger_counter) %>%
    spread(`PROMISE TYPE`, `PROMISES`) %>%
    arrange(`GC TRIGGER`) %>%
    mutate(`CUMULATIVE CREATED` = cumsum(`CREATED`),
           `CUMULATIVE GARBAGE COLLECTED` = cumsum(`GARBAGE COLLECTED`)) %>%
    rowwise() %>%
    mutate(`ALIVE` = `CUMULATIVE CREATED` - `CUMULATIVE GARBAGE COLLECTED` + `GARBAGE COLLECTED`) %>%
    select(-`CUMULATIVE CREATED`, -`CUMULATIVE GARBAGE COLLECTED`)

min_trigger <- min(gc_data$`GC TRIGGER`, na.rm = TRUE)
max_trigger <- max(gc_data$`GC TRIGGER`, na.rm = TRUE)

gc_data <-
    tibble(`GC TRIGGER` = c(min_trigger : max_trigger)) %>%
    full_join(gc_data, by = "GC TRIGGER")

gc_data$`DISPENSABLE` <- 0

data <-
    lifecycle %>%    
    arrange(promise_id) %>%
    collect() %>%
    spread(event_type, gc_trigger_counter) %>%
    rowwise() %>%
    mutate(begin = max(`0`, `1`, na.rm = TRUE) + 1,
           end   = min(`2`, max_trigger + 1, na.rm = TRUE) - 1)

# This is quite slow. Looking for a better solution.
for(i in 1:length(data$begin)) {
    a <- data$begin[i]
    b <- data$end[i]
    if(a <= b)
        gc_data$`DISPENSABLE`[a : b] <- gc_data$`DISPENSABLE`[a : b] + 1;
}

# TODO - Replace NA with 0 to ensure correctness

# Remove last gc trigger data as it will never tells us how many
# promises are garbage collected. It will only have NA. 
gc_data <-
    gc_data %>%
    head(-1) %>%
    mutate(`INDISPENSABLE` = `ALIVE` - `GARBAGE COLLECTED` - `DISPENSABLE`)

scale_x_limits <- c(min_trigger - 1, max_trigger)
scale_x_breaks <- seq(min_trigger, max_trigger - 1, as.integer((max_trigger - min_trigger) / 10))

graph <-
    gc_data %>%
    gather(`PROMISE TYPE`, `PROMISES`, -`GC TRIGGER`) %>%
    ggplot(aes(`GC TRIGGER`, `PROMISES`, group = `PROMISE TYPE`)) +
    geom_bar(aes(fill = `PROMISE TYPE`), stat = "identity", position = "dodge") +
    scale_x_continuous(breaks = scale_x_breaks, limits = scale_x_limits) +
    scale_fill_gdocs()

graph

datatable(gc_data, rownames = FALSE)
```

```{r promise_collection_effectiveness, echo = FALSE}
# this is a dirty hack to get ggplot2 to make the graph.
# Apparently, it is not possible to mix and match stacked 
# and dodged bar charts in ggplot2. Hence, I am modifying the 
# data to get the bar lengths I want.
partial_data <-
    gc_data %>%
    mutate(`DISPENSABLE` = `DISPENSABLE` + `GARBAGE COLLECTED`) %>%
    select(`GC TRIGGER`, `DISPENSABLE`) %>%
    gather(`PROMISE TYPE`, `PROMISES`, -`GC TRIGGER`)
    
graph <-
    gc_data %>%
    select(`GC TRIGGER`, `ALIVE`, `GARBAGE COLLECTED`) %>%
    gather(`PROMISE TYPE`, `PROMISES`, -`GC TRIGGER`) %>%
    ggplot(aes(`GC TRIGGER`, `PROMISES`, group = `PROMISE TYPE`)) +
    geom_bar(data = partial_data, mapping = aes(fill = `PROMISE TYPE`), stat = "identity", position = "dodge") +
    geom_bar(aes(fill = `PROMISE TYPE`), stat = "identity", position = "dodge") +
    scale_x_continuous(breaks = scale_x_breaks, limits = scale_x_limits) +
    scale_fill_gdocs()

graph
```

```{r promise_gc_data_summary_statistics, echo = FALSE}
graph <-
    gc_data %>%
    gather(`PROMISE TYPE`, `PROMISES`, -`GC TRIGGER`) %>%
    ggplot(aes(`PROMISE TYPE`, `PROMISES`)) +
    geom_boxplot() +
    geom_jitter(width = 0.2) +
    scale_color_gdocs()
    
graph

summary_gc_data <-
    gc_data %>%
    select(-`GC TRIGGER`) %>%
    apply(2, function(col) as.vector(summary(col))) %>%
    as.tibble() %>%
    mutate(`STATISTICS` = c("MINIMUM", "1st QUARTILE", "MEDIAN", "MEAN", "3rd QUARTILE", "MAXIMUM")) %>%
    gather(`PROMISE TYPE`, `VALUE`, -`STATISTICS`) %>%
    spread(`STATISTICS`, `VALUE`)
    
datatable(summary_gc_data, rownames = FALSE)    
```
